Add missing "include <memory>" needed for unique_ptr (#2338)
* Add missing "include <memory>" needed for unique_ptr

Fix:
/home/conda/feedstock_root/build_artifacts/colmap_1704738145804/work/src/colmap/image/line.cc: In function 'std::vector<colmap::LineSegment> colmap::DetectLineSegments(const colmap::Bitmap&, double)':
/home/conda/feedstock_root/build_artifacts/colmap_1704738145804/work/src/colmap/image/line.cc:63:8: error: 'unique_ptr' is not a member of 'std'
   63 |   std::unique_ptr<double, RawDeleter> segments_data(
      |        ^~~~~~~~~~
/home/conda/feedstock_root/build_artifacts/colmap_1704738145804/work/src/colmap/image/line.cc:36:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?

* Another missing include

* Update workspace.h

* Update line.cc

---------

Co-authored-by: Johannes Schönberger <jsch@demuc.de>