Bump C++ version as required by CGAL (#853)
In file included from src/mvs/meshing.cc:39:
In file included from /usr/local/include/CGAL/Delaunay_triangulation_3.h:25:
In file included from /usr/local/include/CGAL/Triangulation_3.h:39:
In file included from /usr/local/include/CGAL/Triangulation_data_structure_3.h:35:
/usr/local/include/CGAL/iterator.h:663:11: error: no template named 'decay_t' in namespace 'std'; did you mean
      'boost::decay_t'?
  typedef std::decay_t<typename cpp11::result_of<Op(arg_type)>::type> value_type;
          ^~~~~
/usr/local/include/boost/type_traits/decay.hpp:42:23: note: 'boost::decay_t' declared here
   template <class T> using decay_t = typename decay<T>::type;
                      ^
In file included from src/mvs/meshing.cc:39:
In file included from /usr/local/include/CGAL/Delaunay_triangulation_3.h:25:
In file included from /usr/local/include/CGAL/Triangulation_3.h:39:
In file included from /usr/local/include/CGAL/Triangulation_data_structure_3.h:35:
/usr/local/include/CGAL/iterator.h:1321:44: error: no template named 'index_sequence' in namespace 'std'
auto to_tuple(std::tuple<Args...> &t, std::index_sequence<Is...>)
                                      ~~~~~^
/usr/local/include/CGAL/iterator.h:1321:1: error: 'auto' return without trailing return type; deduced return types are a
      C++14 extension
auto to_tuple(std::tuple<Args...> &t, std::index_sequence<Is...>)
^
/usr/local/include/CGAL/iterator.h:1414:49: error: no member named 'index_sequence_for' in namespace 'std'
    return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                           ~~~~~^
/usr/local/include/CGAL/iterator.h:1414:68: error: 'O' does not refer to a value
    return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                                   ^
/usr/local/include/CGAL/iterator.h:1333:39: note: declared here
template < typename... V, typename... O >
                                      ^
/usr/local/include/CGAL/iterator.h:1419:49: error: no member named 'index_sequence_for' in namespace 'std'
    return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                           ~~~~~^
/usr/local/include/CGAL/iterator.h:1419:68: error: 'O' does not refer to a value
    return tuple_internal::to_tuple(*this, std::index_sequence_for<O...>{});
                                                                   ^
/usr/local/include/CGAL/iterator.h:1333:39: note: declared here
template < typename... V, typename... O >
                                      ^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:25:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:47:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:57:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:66:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:75:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:84:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:93:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:102:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:126:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:135:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:145:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
In file included from src/mvs/meshing.cc:40:
In file included from /usr/local/include/CGAL/Exact_predicates_inexact_constructions_kernel.h:20:
In file included from /usr/local/include/CGAL/Simple_cartesian.h:20:
In file included from /usr/local/include/CGAL/Cartesian/Cartesian_base.h:22:
In file included from /usr/local/include/CGAL/Kernel/global_functions.h:25:
/usr/local/include/CGAL/Kernel/hash_functions.h:154:8: error: no template named 'enable_if_t' in namespace 'std'; did you
      mean 'boost::enable_if_t'?
inline std::enable_if_t<std::is_same<typename K::Rep_tag, Cartesian_tag>::value, std::size_t>
       ^~~~~
/usr/local/include/boost/type_traits/enable_if.hpp:32:1: note: 'boost::enable_if_t' declared here
using enable_if_t = typename enable_if_<B, T>::type;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]